//Jenkinsfile (Declarative Pipeline)
pipeline { 
    agent any  
    stages { 
        stage('Build') { 
            steps { 
               echo 'This is a minimal pipeline.' 
            }
        }
    }
}



node {
   def mvnHome
   stage('Preparation') {
      git url: 'https://github.com/priyanka2596/Java_servlet_2.git'
      mvnHome = tool 'M3'
   }
   stage('Build') {
      sh "'${mvnHome}/bin/mvn' -Dmaven.test.failure.ignore clean package"
   }
